### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by james-k-polk** [jedisct1/libsodium-doc#112]
It is my understanding that the accepted terminology for a key pair in public key (asymmetric) cryptography is **public key** and **private key**.  It seems that you instead used **public key** and **secret key**. This will be confusing to users because your section on symmetric cryptography is called "secret key cryptography". Your docs also conflate the two kinds of keys, e.g. 

> This high-level API encrypts a sequence of messages, or a single message split into an arbitrary number of chunks, using a secret key

in a reference to a symmetric key and

> Using Alice's public key and his secret key, Bob can compute the exact same shared secret key.

in reference to an asymmetric private key.

This is very unfortunate. It seems to have seeped into constants as well, e.g. `crypto_box_SECRETKEYBYTES`. Thus it is probably too late to change.

**Comment by jedisct1** [comment]
Using "private key" and "public key" gets confusing when these are abbreviated, since they both compress to `pk`.

This is why the terminology "secret key" and "public key" is used consistently, as well as `sk`, `pk` to represent them.

"private key" and "secret key" represent the exact same idea of something that should not be predictable by a 3rd party.
