### ISSUE TITLE
Comparison of different hash functions and authentication codes

### ISSUE THREAD

**Issue by pokey** [jedisct1/libsodium-doc#12]
Great docs!  One thing that I think could be clarified:

There are 4 functions that I am having trouble figuring out the difference between:
- `crypto_auth` / `crypto_auth_verify`
- `crypto_generichash`
- `crypto_shorthash`
- `crypto_onetimeauth` / `crypto_onetimeauth_verify`

I can see 3 potential uses for this set of functions:
- hash tables / bloom filters
  - Here, I think it's clear that `crypto_shorthash` is the winner, because it is no worse than any of the other options, and is the most performant of the group.
- creating unique identifiers for arbitrarily long data
  - Here, `crypto_shorthash` and `crypto_onetimeauth` are ineligible due to collisions, and `crypto_auth` has worse performance
- message authentication
  - This is where I get confused.  In the docs, there are 4 use cases that I don't know how to tell apart:
    - integrity checking in interactive protocols (described as use case for  `crypto_shorthash`)
    - file integrity checking (described as use case for `crypto_generichash`)
    - one-time authentication (as per `crypto_onetimeauth`)
    - secret-key authentication (as per `crypto_auth`)

I don't see the difference between the different use cases I've categorized as "message authentication."  I guess the one place I see a comparison drawn in the docs is where `crypto_onetimeauth` is described as ineligible for large messages.  Otherwise, I don't see why I shouldn't (for example) use `crypto_auth` for file integrity checking, or `crypto_generichash` for secret-key authentication.  

I'd love to see either a dedicated section comparing these 4 types of "message authentication," or to have the doc section for each function include a brief comparison to each of the other 3.  Example questions to answer:
- Are there performance tradeoffs?
- Security tradeoffs?
- Why is one ok for one application but not for others?

I think having these sort of comparisons in the documentation would be in line with the overall awesomeness that is libsodium: here are the dozen crypto primitives you need to care about, and here's how you know which one to use.

**Comment by drbo** [comment]
Here is my understanding (not a definitive answer).  Be sure to double-check before relying on any of these statements for production applications.

#### Both `crypto_onetimeauth` and `crypto_onetimeauth_verify` require a non-reusable key
`crypto_onetimeauth` / `crypto_onetimeauth_verify` are ONLY to be used when a unique, unpredictable key can be generated every time.  **If the key is reused even once, then it can be computed by an attacker who has access to the authenticator and authenticated message**.  This is perfectly OK when used as a MAC for a stream cipher (where the first 256 bits of stream cipher output provides a perfectly usable MAC key, since stream ciphers need a nonce anyway) or when a PRP or PRF (such as Blake2b, HSalsa20, or HChaCha20) hides the MAC value from an attacker.  It is NOT okay otherwise.  Its main use is as a MAC in authenticated encryption.

#### Don't use `crypto_shorthash` for long-term security
`crypto_shorthash` is too short to provide long-term security.  However, it is okay in interactive applications where an attacker cannot bring computational power to bear against it and only short-term security is needed.  Furthermore, it is extremely fast &mdash; as fast as some non-cryptographic hash functions.  This makes it suitable for non-cryptographic uses such as hash tables, where the fact that it is a strong PRF means that hash-collision DoS is averted and pathological cases can be avoided.  Be aware that it is NOT collision resistant, though it IS resistant to key-independent collisions and to high-order multicollisions.

#### Both `crypto_onetimeauth` and `crypto_shorthash` require a _secret_ key.
Both `crypto_onetimeauth` and `crypto_shorthash` **require** the secret key, and are subject to first- and second-preimage attacks if the key is discovered by an attacker.

#### Don't use `crypto_hash` (except for compatibility with other programs)
Compared to `crypto_hash` (which uses SHA512), `crypto_generichash` is much faster and is not vulnerable to length-extension attacks.

#### You can use `crypto_generichash` as a MAC, just like `crypto_auth`, with at least the same security and much higher speed
`crypto_auth` is _much_ slower than `crypto_generichash` ([Blake2b is 2-3 times faster than SHA512][1]) and provides no benefit that I know of &mdash; `crypto_generichash` simply prepends the (zero-padded) key to the message, which is considered secure (the [Blake2 documentation][1] implies that Blake2b is not vulnerable to length-extension attacks).

[1]: https://blake2.net/blake2.pdf

**Comment by pokey** [comment]
Great; very helpful, thanks!
